#!/usr/bin/env bash

# Bail out on the first error
set -e

# Pull down the lastest image
/usr/local/bin/docker-compose/docker-compose -f /home/b_one/sites/watchtower-frontend-deploy/docker-compose.yml pull watchtwer_frnt

# Recreate container using the latest image
/usr/local/bin/docker-compose/docker-compose -f /home/b_one/sites/watchtower-frontend-deploy/docker-compose.yml up -d