#!/usr/bin/env bash

# Bail out on the first error
set -e

# Pull down the lastest image
/usr/local/bin/docker-compose/docker-compose pull watchtwer_frnt

# Recreate container using the latest image
/usr/local/bin/docker-compose/docker-compose up -d